### ISSUE TITLE
Model is in floor

### ISSUE THREAD

**Issue by Dryf3535** [Moffein/RocketSurvivor#15]
I dont know if this is just an issue with some other mod or something but my characters model is just always halfway in the floor, otherwise still completely playable just very odd
![image](https://github.com/Moffein/RocketSurvivor/assets/113150559/f6e9898d-ab07-4e95-bd7e-40af8a8c0628)

**Comment by Moffein** [comment]
Could you upload your r2modman profile file when you get the chance?
Settings -> Profile -> Export as File

**Comment by Dryf3535** [comment]
I use Thunderstore so I dont know if that effects it but it wouldnt let me upload the file as its a .r2z 
I did grab the code though if that can help
018e2d58-5363-baa0-2ee5-fa32a59f22d0
(sorry accidentally hit completed, dont use github often)

**Comment by Moffein** [comment]
Seems to be an issue with a recent CustomEmotesAPI.
I'll ask the devs of that mod about this.

In the meantime, you can try out previous versions of the mod to see if that fixes things, since I know it used to work fine earlier.

**Comment by ToastedOven** [comment]
Just letting you know, was absolutely on my end because I have the stupid. It has been fixed in the most recent CustomEmotesAPI patch
