### ISSUE TITLE
Rocketman glaring design issue. 

### ISSUE THREAD

**Issue by Lavoroxan** [Moffein/RocketSurvivor#2]
Good work making a survivor that looks like it was straight out of a content update and also has interesting possibilities for gameplay, but there is one pretty huge gameplay issue i have encountered.

He cannot do the griddy.

Thank you for your time.

**Comment by Moffein** [comment]
Forgot to reply to this way back when I added it, but EmoteAPI support is a thing now, so it's techcnically possible :^) (haven't actually looked through the entire emote list)
