### ISSUE TITLE
Primary Physics Not Functional For Non-Host During Multiplayer

### ISSUE THREAD

**Issue by THE0R** [Moffein/RocketSurvivor#20]
Been playing with my friend and he is experiencing a bug where his primary fire doesn't propel him at all when he plays multiplayer. Issue does not persist for him in singleplayer or for me when I host the lobby. If he hosts the lobby both of us can propel using our primaries, but I have more items unlocked and have a curated item blacklist so we always opt for me to host. Is this a known issue?

**Comment by Moffein** [comment]
Haven't had time to test in-depth, did a quick recompile for the latest update. If it's still broken, let me know.
Note that the default/alt primaries use different methods internally to rocket jump, so it's possible for one to work but not the other.

**Comment by THE0R** [comment]
That's good to know! I didn't even think to mention it, but I use the alternate primary and he uses the default. I couldn't replicate the issue on my end, but that might be because he doesn't have the alternate primary unlocked for him to test it further. The issue didn't persist for him in singleplayer though. We'll test it again to see if the issue is still there.

**Comment by Moffein** [comment]
Released another update today (1.0.10) that swapped the default primary's rocket jumps to use the same method as the alt primary's.
Let me know if it's working, as well as if M2 detonation rocket jumps are working.

**Comment by THE0R** [comment]
Just tested it with him, works great! Thanks so much! We are truly undeserving of your diligence sir!
