### ISSUE TITLE
Missing animation pet peeve

### ISSUE THREAD

**Issue by BitzThe8Bit** [Moffein/RocketSurvivor#7]
The missing animation I'm talking about is the one where you stop inputting movement keys and your character does a short animation before transitioning to their idle standing pose. Rocket, unlike most vanilla (and some modded) survivors, is missing this animation, so he just jerks back into his idle pose when you stop inputting keys, which is slightly jarring to look at if you're paying close attention to the funny green explosion man.
This obviously is such a small thing that like 5 people care about (including me), so I won't lose sleep if ya'll don't add or care about it, I just wanted to get this out here before I forgot to do it again.

**Comment by TheTimeSweeper** [comment]
have you ever noticed railgunner doesn't have this either. if you haven't now you know :P

**Comment by Moffein** [comment]
Update is live, thanks for reporting this.

**Comment by BitzThe8Bit** [comment]
> have you ever noticed railgunner doesn't have this either. if you haven't now you know :P

Yeah, that's why I said _most_ survivors, I knew engie and railgunner for sure didn't have those animations, I think void fiend doesn't either. My head canon for the lack of engie stop animations is due to the fact that the sprint and walk animations are so different from one another that they couldn't possibly make an animation that looked okay for both.
Oh man, I was just reminded of something, I knew I forgot something in this issue (which is also a pet peeve of mine lol), and it's the fact that Rocket doesn't have footstep sounds, but anyways, that is all for me I think.
